name: CI

on: ["push", "pull_request"]

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Python 3.8"
            python: "3.8"
            experimental: false
            coverage: false
          - name: "Python 3.9"
            python: "3.9"
            experimental: false
            coverage: true
          - name: "Python 3.10"
            python: "3.10"
            experimental: false
            coverage: false

    name: ${{ matrix.name }}
    runs-on: "ubuntu-20.04"
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - uses: actions/checkout@v2
      - name: "Set up Python ${{ matrix.python }}"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: "Cache dependencies"
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python }}-pip-${{ hashFiles('setup.cfg') }}-${{ hashFiles('tasks.py') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python }}-pip-
      - name: "Install dependencies"
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install .[dev]
      - name: "Run linting"
        run: python3 -m invoke lint
      - name: "Run type checking"
        run: python3 -m invoke type-check
      - name: "Run tests"
        run: python3 -m invoke test
      - name: "Test building package"
        run: python3 -m build
      - name: "Upload coverage data to Codecov"
        uses: codecov/codecov-action@v2
        if: ${{ matrix.coverage }}
